v1.37

diff --git a/create-pcr b/create-pcr
--- a/create-pcr
+++ b/create-pcr
@@ -1,66 +1,165 @@
 #!/bin/bash
 
-# YSA PCR V1.36 - create PCR (pacman cache repository)
-# http://www.kaskus.co.id/thread/51dbb48d6212432422000001/arch-linux-community---part-1/
+# PCR (Pacman Cache Repository) Script (v1.37)
+# https://github.com/yadieet/pcr
 #
 # yadieet sa <qts19bit@gmail.com>
 
+
 if [[ $EUID == 0 ]]; then
-   echo "Sorry but don't run this script as root user."
+   echo "Sorry but don't run this script root."
    exit
 fi
 
+
 if [[ -z $@ ]]; then
-	echo Missing arguments !
-	echo Please give some repox arguments ! \(Example: core extra community multilib mate\)
+	echo "Cannot continue, missing arguments. (Use -h for help)"
+	echo "Example : $ create-pcr -r \"core extra community multilib mate\" -o \"/data/\" -cp 0 -pi 1"
 	exit
 fi
 
-for repox in $@
+for arg in "$@"
+do
+	if [[ $arg == "-h" ]]; then
+
+echo "PCR (Pacman Cache Repository) Script (v1.37)"
+echo "-- Create local repository from pacman cache."
+echo "https://github.com/yadieet/pcr"
+echo ""
+echo "OPTIONS :"
+echo "-r  : repositories, example : \"core extra community multilib mate\""
+echo "-o  : output directory, must already exist. This script will create the 'PCR' directory under output directory."
+echo "-cp : copy mode (default is '0'). If value is not '1', use linking mode."
+echo "-pi : prefer installed (default is '1'). Use installed version of package if the current version and installed version of package are exists."
+echo ""
+echo "Example usage :"
+echo "$ create-pcr -r \"core extra community multilib mate\" -o \"/data/\" -cp 0 -pi 1"
+		exit
+	fi
+done
+
+repoxs=0
+iarg=1
+for arg in "$@"
+do
+	((iarg++))
+	if [[ $arg == "-r" ]]; then
+		repoxs=${@:$iarg:1}
+		break
+	fi
+done
+if [[ $repoxs == 0 || -z $repoxs ]]; then
+	echo "Cannot continue, please give some repoxs. (Example: -r \"core extra community multilib mate\")"
+	exit
+fi
+if [[ ${repoxs:0:1} == '-' ]]; then
+	echo "Invalid args for -r ."
+	exit
+fi
+
+for repox in $repoxs
 do
 	pkglist=`pacman -Sl $repox`
 	if [[ -z `echo "$pkglist" | awk {'print $1'}` ]]; then
-		echo "Repox '$repox' was not found."
+		echo "Repox '$repox' not exist."
 		exit
 	fi
 done
 
 pacman_cache_dir="/var/cache/pacman/pkg/"
-prefer_installed=1
+if [ ! -d "$pacman_cache_dir" ]; then
+	echo "Cannot continue, pacman cache directory '$pacman_cache_dir' is not exist."
+	exit
+fi
+if [ ! -r "$pacman_cache_dir" ]; then
+	echo "Cannot continue, pacman cache directory '$pacman_cache_dir' is not readable."
+	exit
+fi
+
+outdir=0
+iarg=1
+for arg in "$@"
+do
+	((iarg++))
+	if [[ $arg == "-o" ]]; then
+		outdir=${@:$iarg:1}
+		break
+	fi
+done
+if [[ "$outdir" == 0 || -z "$outdir" ]]; then
+	echo "Cannot continue, please specify output directory. (Example: -o \"/data/\" )"
+	exit
+fi
+if [ ! -d "$outdir" ]; then
+	echo "Cannot continue, output directory '$outdir' is not exist."
+	exit
+fi
+if [ ! -w "$outdir" ]; then
+	echo "Cannot continue, output directory '$outdir' is not writable."
+	exit
+fi
+
 copying=0
-basepath="/data/"
-outdir="PCR"
+iarg=1
+for arg in "$@"
+do
+	((iarg++))
+	if [[ $arg == "-cp" ]]; then
+		copying=${@:$iarg:1}
+		break
+	fi
+done
+if [[ "$copying" != 0 && $copying != 1 ]]; then
+	copying=0
+fi
+
+prefer_installed=1
+iarg=1
+for arg in "$@"
+do
+	((iarg++))
+	if [[ $arg == "-pi" ]]; then
+		prefer_installed=${@:$iarg:1}
+		break
+	fi
+done
+if [[ "$prefer_installed" != 0 && $prefer_installed != 1 ]]; then
+	prefer_installed=1
+fi
+
+echo "Configuration :"
+echo "==============="
+echo "Pacman cache directory         = '$pacman_cache_dir'"
+echo "Repositories (-r)              = $repoxs"
+echo "Output directory (-o)          = '$outdir'"
+echo -n "Copy mode (-cp)                = ";  [[ $copying == 0 ]] && echo "no (linking)" || echo "yes"
+echo -n "Prefer installed version (-pi) = ";  [[ $prefer_installed == 0 ]] && echo "no" || echo "yes"
+echo ""
+
 arch=`uname -m`
 
-if [ ! -e "$basepath" ]; then
-		echo "Cannot continue, path '$basepath' doesn't extst !"
+cd "$outdir"
+if [ -e "PCR" ]; then
+		echo "Cannot continue, 'PCR' directory in '$outdir' exist. Please remove 'PCR' directory first."
 		exit
 fi
-
-cd "$basepath"
-
-if [ -e "$outdir" ]; then
-		echo Cannot continue, output directory exist. Please remove first !
-		exit
-fi
-
-mkdir -p "$outdir/archlinux"
-cd "$outdir/archlinux"
+mkdir -p "PCR/archlinux"
+cd "PCR/archlinux"
 
 t=0
 
 function copyx() {
-	t=$(($t+1))
+	((t++))
 	echo "#"$t: Copying `ls $1` to [$2] directory.. [$3]
 	cp -L $1 $2/os/$arch
 }
 function linkingx() {
-	t=$(($t+1))
+	((t++))
 	echo "#"$t: Linking `ls $1` to [$2] directory.. [$3]
 	ln -s $1 $2/os/$arch
 }
 
-for repox in $@
+for repox in $repoxs
 do
 	mkdir -p $repox/os/$arch
 		pkglist=`pacman -Sl $repox`
@@ -111,12 +210,11 @@ do
 		done < <(echo "$pkglist")
 done
 
-for repox in $@
+for repox in $repoxs
 do
-	cd "$basepath/$outdir/archlinux/$repox/os/$arch"
+	cd "$outdir/PCR/archlinux/$repox/os/$arch"
 	repo-add $repox.db.tar.gz *.pkg.tar.xz
 done
 
 echo "======================================="
-echo "Finished. Have a lovely beautiful day.."
 echo "Total: $t packages."
